### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by gonutz** [DGH2112/Debugging-Tools#4]
Hey there, this is not really an issue but these days there is no way to reach out to someone via a private message on Github.

I just wanted to thank you for putting your various Delphi plugins up online for everyone to see. I was having a hard time finding useful and complete information about how to build one and this very repo just worked out of the box, supports all Delphi versions and has great documentation, including that on your website. I just wanted to say thank you for sharing all of this information. With it I was able to create the simplest of plugins [Open in Vim](https://github.com/gonutz/OpenInVim) and I now have a starting point to create more complex things in the future.

I do not take for granted when people create good content like yours, that is why I wanted to say thank you. That is the least I can do.

👍 👍 👍 

PS.: feel free to close this "issue" ;-D

**Comment by DGH2112** [comment]
Thank you for the "issue". It's nice to know what I do is useful to others.
If you are learning OTA, then checkout all the articles and book on my [website](https://www.davidghoyle.co.uk/WordPress/).
regards
Dave.
