### ISSUE TITLE
How to install the resulting DGHDebuggingToolsRSxxx.dll in the RADStudio IDE ?

### ISSUE THREAD

**Issue by dcabale** [DGH2112/Debugging-Tools#5]
Hello,
I know how to install a Delphi package (.bpl) in the IDE : menu > Component > Install Package ... > "Add" button, .. and all is fine, the package is added.
As this project is a .dll project (it produces DGHDebuggingToolsRSxxx.dll), how do you install it in the Delphi IDE ?
Sorry if that question seems obvious for you, but I did not find any useful information neither on the web, nor on your Wiki page.
Thanks for your help.

**Comment by dcabale** [comment]
I think I found the answer in your "The Delphi IDE Open Tools API - Version 1.2.docx" documentation:
![image](https://user-images.githubusercontent.com/1404724/159966357-acf0b962-a8e7-4fc7-88c7-c0863a6a2a16.png)
Of course, the registry path is slightly different..
![image](https://user-images.githubusercontent.com/1404724/159969303-28252c94-f048-4a4f-97aa-04e240b8c077.png)
-> instead of “My Computer\HKEY_CURRENT_USER\Software\Borland\BDS\4.0\”, it is now "Computer\HKEY_CURRENT_USER\Software\Embarcadero\BDS\xx.x\Experts"
.. and the result is pretty what's expected!
![image](https://user-images.githubusercontent.com/1404724/159969851-c34dbe48-db8f-4bda-9ae6-0f663e1471af.png)

**Comment by DGH2112** [comment]
If you want a GUI way of doing it then you can either use GExpert's Expert Manager or my own [Multi-IDE Expert Manager](https://www.davidghoyle.co.uk/WordPress/?page_id=1361).

**Comment by dcabale** [comment]
Why not installing package .bpl instead of library .dll, and the GUI will be the IDE itself.
I guess the reason is because you don't want to rely on the IDE for managing the plugins, isn't it?

**Comment by DGH2112** [comment]
If prefer DLL as I can manage them with a single code base, i.e. 1 .DPR file. You cannot do that with a .DPK file as the IDE manage those so you need a .DPK file for each IDE you are supporting. The 1 .DPR file supports multiple IDEs through the use of a .INC file which sets the library extension based on compiler directives.
